/*
 * Tribufu API
 *
 * REST API to access Tribufu services.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: contact@tribufu.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum GroupRank {
    #[serde(rename = "member")]
    Member,
    #[serde(rename = "leader")]
    Leader,
    #[serde(rename = "owner")]
    Owner,

}

impl std::fmt::Display for GroupRank {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Member => write!(f, "member"),
            Self::Leader => write!(f, "leader"),
            Self::Owner => write!(f, "owner"),
        }
    }
}

impl Default for GroupRank {
    fn default() -> GroupRank {
        Self::Member
    }
}

