/*
 * Tribufu API
 *
 * REST API to access Tribufu services.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: contact@tribufu.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RevokeRequest {
    #[serde(rename = "token", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub token: Option<Option<String>>,
    #[serde(rename = "token_type_hint", skip_serializing_if = "Option::is_none")]
    pub token_type_hint: Option<models::TokenHintType>,
}

impl RevokeRequest {
    pub fn new() -> RevokeRequest {
        RevokeRequest {
            token: None,
            token_type_hint: None,
        }
    }
}

