/*
 * Tribufu API
 *
 * REST API to access Tribufu services.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: contact@tribufu.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerMetrics {
    #[serde(rename = "server_count", skip_serializing_if = "Option::is_none")]
    pub server_count: Option<i32>,
    #[serde(rename = "package_count", skip_serializing_if = "Option::is_none")]
    pub package_count: Option<i32>,
    #[serde(rename = "country_count", skip_serializing_if = "Option::is_none")]
    pub country_count: Option<i32>,
}

impl ServerMetrics {
    pub fn new() -> ServerMetrics {
        ServerMetrics {
            server_count: None,
            package_count: None,
            country_count: None,
        }
    }
}

