/*
 * Tribufu API
 *
 * REST API to access Tribufu services.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: contact@tribufu.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TokenHintType {
    #[serde(rename = "access_token")]
    AccessToken,
    #[serde(rename = "refresh_token")]
    RefreshToken,

}

impl std::fmt::Display for TokenHintType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::AccessToken => write!(f, "access_token"),
            Self::RefreshToken => write!(f, "refresh_token"),
        }
    }
}

impl Default for TokenHintType {
    fn default() -> TokenHintType {
        Self::AccessToken
    }
}

